name: Deploy

on: push

jobs:   
  deploy:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: thomasjeanlouis1/gameserver:${{ github.ref_name }}_${{ github.run_number }}
      - run: >
          curl -L
          -X PATCH \=
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}"
          -H "X-GitHub-Api-Version: 2022-11-28"
          https://api.github.com/repos/thomasjean-louis/infra/environments/${{ github.ref_name }}/variables/GAME_SERVER_DOCKER_IMAGE
          -d '{"name":"GAME_SERVER_DOCKER_IMAGE","value":"${{ github.ref_name }}_${{ github.run_number }}"}'
